config/routes.rb
Rails.application.routes.draw do

  resources :pets

  get '/found', to: 'pets#found'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pet.rb
class Pet < ApplicationRecord
  CATEGORIES = ["cat", "dog", "fish", "bird", "rabbit", "cow"]

  validates :name, presence: true
  validates :category, inclusion: { in: CATEGORIES }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :pet, only: [:edit, :show, :update, :destroy]
  def index
    @pets = Pet.where(found_on: nil)
  end

  def found
    @pets = Pet.all
  end

  def show
  end

  def new
    @pet = Pet.new(name: params[:name], category: params[:category], address: params[:address], found_on: params[:found_on] )
  end

  def create
    @pet = Pet.new(pet_params)
    @pet.save
    redirect_to pets_path
  end

  def edit
  end

  def update
    @pet.update(pet_params)
    redirect_to pets_path
  end

  def destroy
    @pet.destroy
    redirect_to pets_path
  end

  private
  def pet_params
    params.require(:pet).permit(:name, :category, :address, :found_on)
  end

  def pet
    @pet = Pet.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LostAndFound</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pets/edit.html.erb
<nav class="navbar navbar-inverse navbar-static-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= pets_path %>">Lost and Found</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-right" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="#">Lost Pets</a></li>
        <li><a href="<%= found_path %>">Found Pets</a></li>
        <li><a href="<%= new_pet_path %>">I lost my pet</a></li>
        <li><a href="#">pointless link</a></li>
      </ul>
      <form class="navbar-form navbar-right" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-success">Submit</button>
      </form>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<div class="banner header">
</div>
<div class="row">
  <div class="col-sm-4 col-sm-offset-4">

    <%= form_for(@pet) do |f| %>
        <div class="form-group">
          <%= f.label :name, value: "name"%>
          <%= f.text_field :name, class: "form-control" %>

          <%= f.label :category %>
          <%= f.text_field :category, class: "form-control" %>

          <%= f.label :address %>
          <%= f.text_field :address, class: "form-control" %> <br>

          <%= f.label :found_on %>
          <%= f.date_select :found_on, class: "form-control" %> <br>

          <br>
          <%= f.submit class: "btn btn-info" %>
        </div>
    <% end %>
  </div>
</div>

app/views/pets/found.html.erb
<nav class="navbar navbar-inverse navbar-static-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= pets_path %>">Lost and Found</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-right" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="<%= pets_path %>">Lost Pets</a></li>
        <li class="active"><a href="#">Found Pets</a></li>
        <li><a href="<%= new_pet_path %>">I lost my pet</a></li>
        <li><a href="#">pointless link</a></li>
      </ul>
      <form class="navbar-form navbar-right" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-success">Submit</button>
      </form>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<div class="banner header">
</div>
<div class="container">
  <div class="row">
    <% @pets.each do |pet|  %>
        <div class="col-xs-12 col-sm-4">
          <div class="card pets">
            <div class="card-block">
              <h3 class="card-title"><%= pet.name %></h3>
              <p class="card-text"><%= pet.category %></p>
              <p class="card-text"><%= pet.address %></p>
              <p class="card-text"><%= pet.found_on %></p>
              <a href="<%= pet_path(pet.id) %>" class="btn btn-primary bottomaligned">Read more</a>
            </div>
          </div>
        </div>
    <% end %>
  </div>
</div>

app/views/pets/index.html.erb
<nav class="navbar navbar-inverse navbar-static-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= pets_path %>">Lost and Found</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-right" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Lost Pets</a></li>
        <li><a href="<%= found_path %>">Found Pets</a></li>
        <li><a href="<%= new_pet_path %>">I lost my pet</a></li>
        <li><a href="#">pointless link</a></li>
      </ul>
      <form class="navbar-form navbar-right" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button href="www.google.com" type="submit" class="btn btn-success">Submit</button>
      </form>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<div class="banner header">
</div>
<div class="container">
  <div class="row">
    <% @pets.each do |pet|  %>
        <div class="col-xs-12 col-sm-4">
          <div class="card pets">
            <div class="card-block">
              <h3 class="card-title"><%= pet.name %></h3>
              <p class="card-text"><%= pet.category %></p>
              <p class="card-text"><%= pet.address %></p>
              <p class="card-text"><%= pet.found_on %></p>
              <a href="<%= pet_path(pet.id) %>" class="btn btn-primary bottomaligned">Read more</a>
            </div>
          </div>
        </div>
    <% end %>
  </div>
</div>

app/views/pets/new.html.erb
<nav class="navbar navbar-inverse navbar-static-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= pets_path %>">Lost and Found</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-right" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="<%= pets_path %>">Home</a></li>
        <li class="active"><a href="<%= new_pet_path %>">New Pet</a></li>
        <li><a href="#">pointless link</a></li>
      </ul>
      <form class="navbar-form navbar-right" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-success">Submit</button>
      </form>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<div class="banner header">
</div>
<div class="row">
  <div class="col-sm-4 col-sm-offset-4">

    <%= form_for(@pet) do |f| %>
        <div class="form-group">
        <%= f.label :name, value: "name"%>
        <%= f.text_field :name, class: "form-control" %> <br>

        <%= f.label :category %>
        <%= f.select :category, options_for_select(Pet::CATEGORIES) %> <br>

        <%= f.label :address %>
        <%= f.text_field :address, class: "form-control" %> <br>

        <%= f.submit class: "btn btn-info" %>
        </div>
    <% end %>
  </div>
</div>

app/views/pets/show.html.erb
<nav class="navbar navbar-inverse navbar-static-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Lost and Found</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-right" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Home</a></li>
        <li><a href="<%= new_pet_path %>">New Pet</a></li>
        <li><a href="<%= pets_path %>">back</a></li>
      </ul>
      <form class="navbar-form navbar-right" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-success">Submit</button>
      </form>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<div class="banner header">
</div>
<div class="container">
  <div class="row">
        <div class="col-sm-4 col-sm-offset-4">
          <div class="card pet">
            <div class="card-block">
              <h3 class="card-title"><%= @pet.name %></h3>
              <p class="card-text"><%= @pet.category %></p>
              <p class="card-text"><%= @pet.address %></p>
              <p class="card-text"><%= @pet.found_on %></p>
              <a href="<%= pet_path(@pet.id) %>" class="btn btn-primary bottomaligned">Read more</a><br><br>
              <a href="<%= edit_pet_path %>" class="btn btn-success bottomaligned">Found Pet</a>
            </div>
          </div>
        </div>
  </div>
</div>